import './globals.css'
import styles from '../app/styles/layout.module.css'
import { Poppins } from 'next/font/google'
import MenuIcon from '@mui/icons-material/Menu';
import DarkModeIcon from '@mui/icons-material/DarkMode';
import Image from 'next/image';

const poppins = Poppins({ 
  subsets: ['latin'] ,
  weight: ['100','200','300','400','500','600','700','800','900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className={styles.headerMenu}>
          <div className={styles.navbar}>
            <div>
             <MenuIcon fontSize='large' className={styles.icon}/>
            </div>
            <div style={{display: 'flex', alignItems: 'center' ,flexDirection: 'row'}}>
              <DarkModeIcon fontSize='large' sx={{borderRadius: '20px', marginRight: '10px'}} className={styles.icon} />
              <Image src="/images/Avatar.png" width={40} height={40} style={{borderRadius: '20px'}}  alt="avatar"  />
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
